### ISSUE TITLE
Mute-Icon appears to be broken

### ISSUE THREAD

**Issue by mpotthoff** [timschumi/gmod-discord#1]
Hey!

First of all - Thanks a lot for this addon! I actually built exactly the same back in 2018 when Discord wasn't filtering the User-Agent yet. We just decided that 2020 would be the year of Garry's Mod again so I discovered your chttp project while I was working on a gmod curl wrapper myself to get around the User-Agent problem... Which brought me to this project. So thank you that I won't have to keep maintaining my own addon!

One thing that's not working for me is the mute-icon on the client. I remember that I had exactly the same problem with my addon which was the reason why I removed the icon from mine.
I'm wondering whether I'm missing something to make it work or if it's just caused by the fact that the addon is loaded from the server and not installed on the client using the workshop.

If this is a known issue with no proper solution yet I would love a config parameter to disable the icon.

A screenshot for reference:
![Screenshot](https://user-images.githubusercontent.com/2939446/73615086-5b5fb080-4605-11ea-9dad-9d383041e370.png)

**Comment by timschumi** [comment]
> One thing that's not working for me is the mute-icon on the client. I remember that I had exactly the same problem with my addon which was the reason why I removed the icon from mine.
> I'm wondering whether I'm missing something to make it work or if it's just caused by the fact that the addon is loaded from the server and not installed on the client using the workshop.

I haven't tested the addon in a non-workshop client/server setup in a while, but I can't see a reason why it wouldn't work. The file seems to be successfully registered for transfer to the client. Anyways, I can test this later and see if I get the same issue.

Also, if that helps, the plugin is [available on the workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=1908490932), I just haven't linked it on GitHub yet.

> If this is a known issue with no proper solution yet I would love a config parameter to disable the icon.

I'll think about it in case I have the same issue and can't fix it, but the "better" solution would probably be to check whether the file exists, and not render the thing if it isn't present.

**Comment by mpotthoff** [comment]
> Also, if that helps, the plugin is available on the workshop, I just haven't linked it on GitHub yet.

Oh. Well. I have to admit that I didn't search the workshop for this addon - I just assumed you hadn't published it yet. It works with the workshop version as expected.

> Anyways, I can test this later and see if I get the same issue.

The issue is solved for me so I'm going to close this. Feel free to reopen it if you still want to look into this.

Thanks again for the great addon and the help! (And you should really link your workshop addon for anyone else who stumbles upon this repo)

**Comment by timschumi** [comment]
Can't reproduce locally unfortunately. Could you share some details about your setup (and whether the game outputs anything on the console related to downloading that icon)?

**Comment by mpotthoff** [comment]
Okay weird. We managed to reproduce it on my server only. In the end it turned out that for some reason `sv_allowdownload` was inferred as 0. Adding `sv_allowdownload 1` to the `server.cfg` fixed the problem.
